nameOverride: ""
fullnameOverride: ""

probes: {}
#  api:
#    enabled: false
#    selector:
#      prometheus: main
#    spec:
#      jobName: "api"
#      module: http_2xx
#      prober:
#        url: '{{ .Values.global.svc.prometheus.blackbox }}:9115'
#      # Static targets:
#      targets:
#        staticConfig:
#          static:
#            - https://api.prd.example.com/api/health
#      # Ingress targets (as used by the argocd chart):
#      targets:
#        ingress:
#          selector:
#            matchLabels:
#              app.kubernetes.io/name: argocd-server
#          namespaceSelector:
#            any: true
