---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - vedro.svetoch.dev
  resources:
  - bucketAccesss
  - buckets
  - cloudprincipals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vedro.svetoch.dev
  resources:
  - bucketAccesss/finalizers
  - buckets/finalizers
  - cloudprincipals/finalizers
  verbs:
  - update
- apiGroups:
  - vedro.svetoch.dev
  resources:
  - bucketAccesss/status
  - buckets/status
  - cloudprincipals/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - vedro.svetoch.dev
  resources:
  - providerconfigs
  verbs:
  - create
  - get
  - list
  - update
  - watch
