---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vedro.svetoch.dev
  resources:
  - bucketaccesses
  - buckets
  - cloudprincipalauths
  - cloudprincipals
  - providerconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vedro.svetoch.dev
  resources:
  - bucketaccesses/finalizers
  - buckets/finalizers
  - cloudprincipalauths/finalizers
  - cloudprincipals/finalizers
  - providerconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - vedro.svetoch.dev
  resources:
  - bucketaccesses/status
  - buckets/status
  - cloudprincipalauths/status
  - cloudprincipals/status
  - providerconfigs/status
  verbs:
  - get
  - patch
  - update
