{{- define "core.configMap" -}}
{{- $ := index . 0 }}
{{- $labels := index . 1 }}
{{- $obj := include "core.obj.enricher" (list $ $labels (index . 2)) | fromYaml }}
{{- if $obj.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
{{- include "core.labels.constructor" (list $ $labels $obj) | nindent 4 }}
  {{- with $obj.annotations }}
  annotations:
  {{- tpl (toYaml .) $ | nindent 4 }}
  {{- end }}
  name: {{ tpl $obj.name $ }}
  namespace: "{{ $obj.namespace }}"
{{- with $obj.immutable }}
immutable: {{ . }}
{{- end }}
data:
{{- range $dataKey, $dataValue := $obj.data }}
  {{ $dataKey }}: |-
{{ tpl (toString $dataValue) $ | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
