apiVersion: vedro.svetoch.dev/v1alpha1
kind: ProviderConfig
metadata:
  labels:
    app.kubernetes.io/name: vedro
    app.kubernetes.io/managed-by: kustomize
  name: providerconfig-sample-gcp
spec:
  type: gcp
  projectId: ${GCP_PROJECT_ID}
  region: europe-west2
  method: WorkloadIdentity
  usagePolicy:
    allowedNamespaces:
      names:
        - vedro-system
    bucketPolicy:
      allowedNamePatterns:
        - '^.*sample.*$'
    principalPolicy:
      allowedNamePatterns:
        - '^.*sample.*$'
      allowedReferencePatterns:
        - '^.*$'

---
apiVersion: vedro.svetoch.dev/v1alpha1
kind: Bucket
metadata:
  labels:
    app.kubernetes.io/name: vedro
    app.kubernetes.io/managed-by: kustomize
  name: bucket-sample-gcp
  namespace: vedro-system
spec:
  providerRef:
    name: providerconfig-sample-gcp
  location: europe-west1

  deletionPolicy: Delete
  publicAccessPrevention: false
  storageClass: Standard

  versioning:
    enabled: true

  lifecycle:
    rules:
      - enabled: true
        ageDays: 90
        action: Delete

  labels:
    app: payments
    env: dev
---
apiVersion: vedro.svetoch.dev/v1alpha1
kind: CloudPrincipal
metadata:
  labels:
    app.kubernetes.io/name: vedro
    app.kubernetes.io/managed-by: kustomize
  name: principal-sample-gcp
  namespace: vedro-system
spec:
  providerRef:
    name: providerconfig-sample-gcp
  kind: ServiceAccount
  managementPolicy: Managed
  managed:
    name: principal-sample-gcp
    deletionPolicy: Delete
---
apiVersion: vedro.svetoch.dev/v1alpha1
kind: BucketAccess
metadata:
  labels:
    app.kubernetes.io/name: vedro
    app.kubernetes.io/managed-by: kustomize
  name: access-sample-gcp
  namespace: vedro-system
spec:
  principalRef:
    name: principal-sample-gcp
    namespace: vedro-system
  bucketRef:
    name: bucket-sample-gcp
    namespace: vedro-system
  access:
    level: ObjectReader
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bucket-list-sample-gcp
  namespace: vedro-system
---
apiVersion: vedro.svetoch.dev/v1alpha1
kind: CloudPrincipalAuth
metadata:
  labels:
    app.kubernetes.io/name: vedro
    app.kubernetes.io/managed-by: kustomize
  name: principal-auth-sample-gcp
  namespace: vedro-system
spec:
  principalRef:
    name: principal-sample-gcp
    namespace: vedro-system
  method: WorkloadIdentity
  workloadIdentity:
    serviceAccountRef:
      name: bucket-list-sample-gcp
    deletionPolicy: Delete
---
apiVersion: batch/v1
kind: Job
metadata:
  name: list-bucket-sample-gcp
  namespace: vedro-system
spec:
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: bucket-list-sample-gcp
      restartPolicy: OnFailure
      containers:
        - name: gcloud
          image: gcr.io/google.com/cloudsdktool/google-cloud-cli:stable
          command: ["gcloud"]
          args:
            - storage
            - ls
            - --recursive
            - gs://bucket-sample-gcp
