apiVersion: vedro.svetoch.dev/v1alpha1
kind: ProviderConfig
metadata:
  labels:
    app.kubernetes.io/name: vedro
    app.kubernetes.io/managed-by: kustomize
  name: providerconfig-sample-gcp
spec:
  type: GCP
  projectId: ${GCP_PROJECT_ID}
  region: europe-west2
  method: StaticCredentials
  credentialsSecretRef:
    name: gcp-creds
    namespace: vedro-system
---
apiVersion: vedro.svetoch.dev/v1alpha1
kind: Bucket
metadata:
  labels:
    app.kubernetes.io/name: vedro
    app.kubernetes.io/managed-by: kustomize
  name: bucket-sample-gcp
  namespace: vedro-system
spec:
  providerRef:
    name: providerconfig-sample-gcp
  location: europe-west1

  deletionPolicy: Retain
  publicAccessPrevention: false
  storageClass: Standard

  versioning:
    enabled: true

  lifecycle:
    rules:
      - enabled: true
        ageDays: 90
        action: Delete

  labels:
    app: payments
    env: dev

  unsupportedFeaturePolicy: Fail
