apiVersion: vedro.svetoch.dev/v1alpha1
kind: ProviderConfig
metadata:
  labels:
    app.kubernetes.io/name: vedro
    app.kubernetes.io/managed-by: kustomize
  name: providerconfig-sample-gcp
spec:
  type: GCP
  projectId: "dexfinance-internal"
  region: europe-west2
  method: StaticCredentials
  credentialsSecretRef:
    name: gcp-creds
    namespace: vedro-system
